apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  labels:
    # serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/triggermesh/flask_project_default/
